# Generated by Django 4.2.15 on 2025-05-14 11:08

from django.db import migrations
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ("user_profile", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="nationality",
            field=django_countries.fields.CountryField(
                blank=True,
                help_text="The nationality of the user",
                max_length=2,
                null=True,
                verbose_name="Nationality",
            ),
        ),
    ]
