# Generated by Django 4.2.15 on 2025-05-14 11:12

import datetime
import django.core.validators
from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ("user_profile", "0002_alter_profile_nationality"),
    ]

    operations = [
        migrations.AlterField(
            model_name="nextofkin",
            name="address",
            field=models.CharField(
                blank=True,
                help_text="The address of the next of kin",
                max_length=12,
                null=True,
                verbose_name="Address",
            ),
        ),
        migrations.AlterField(
            model_name="nextofkin",
            name="city",
            field=models.CharField(
                blank=True,
                help_text="The city of the next of kin",
                max_length=12,
                null=True,
                verbose_name="City",
            ),
        ),
        migrations.AlterField(
            model_name="nextofkin",
            name="date_of_birth",
            field=models.DateField(
                blank=True,
                help_text="The date of birth of the next of kin",
                null=True,
                verbose_name="Date of Birth",
            ),
        ),
        migrations.AlterField(
            model_name="nextofkin",
            name="email_address",
            field=models.EmailField(
                blank=True,
                help_text="The email address of the next of kin",
                max_length=254,
                null=True,
                verbose_name="Email Address",
            ),
        ),
        migrations.AlterField(
            model_name="nextofkin",
            name="first_name",
            field=models.CharField(
                blank=True,
                help_text="The first name of the next of kin",
                max_length=12,
                null=True,
                verbose_name="First Name",
            ),
        ),
        migrations.AlterField(
            model_name="nextofkin",
            name="last_name",
            field=models.CharField(
                blank=True,
                help_text="The last name of the next of kin",
                max_length=12,
                null=True,
                verbose_name="Last Name",
            ),
        ),
        migrations.AlterField(
            model_name="nextofkin",
            name="other_names",
            field=models.CharField(
                blank=True,
                help_text="The other names of the next of kin",
                max_length=12,
                null=True,
                verbose_name="Other Names",
            ),
        ),
        migrations.AlterField(
            model_name="nextofkin",
            name="phone_number",
            field=phonenumber_field.modelfields.PhoneNumberField(
                blank=True,
                help_text="The phone number of the next of kin",
                max_length=128,
                null=True,
                region=None,
                verbose_name="Phone Number",
            ),
        ),
        migrations.AlterField(
            model_name="nextofkin",
            name="relationship",
            field=models.CharField(
                blank=True,
                help_text="The relationship of the next of kin",
                max_length=12,
                null=True,
                verbose_name="Relationship",
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="address",
            field=models.CharField(
                blank=True,
                help_text="The address of the user",
                max_length=12,
                null=True,
                verbose_name="Address",
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="annual_income",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="The annual income of the user",
                max_digits=10,
                null=True,
                verbose_name="Annual Income",
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="date_of_birth",
            field=models.DateField(
                blank=True,
                help_text="The date of birth of the user",
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(datetime.date(1900, 1, 1))
                ],
                verbose_name="Date of Birth",
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="date_of_employment",
            field=models.DateField(
                blank=True,
                help_text="The date of employment of the user",
                null=True,
                verbose_name="Date of Employment",
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="employer_name",
            field=models.CharField(
                blank=True,
                help_text="The name of the employer of the user",
                max_length=12,
                null=True,
                verbose_name="Employer Name",
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="identification_expiry_date",
            field=models.DateField(
                blank=True,
                help_text="The expiry date of the identification of the user",
                null=True,
                verbose_name="Identification Expiry Date",
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="identification_issue_date",
            field=models.DateField(
                blank=True,
                help_text="The issue date of the identification of the user",
                null=True,
                verbose_name="Identification Issue Date",
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="identification_number",
            field=models.CharField(
                blank=True,
                help_text="The identification number of the user",
                max_length=12,
                null=True,
                verbose_name="Identification Number",
            ),
        ),
    ]
